stages:
- build
- deploy

preview:
  image: node:lts
  stage: deploy
  cache: {}
  before_script:
  - npm install
  script:
  - mkdir -p cache/
  - npm run build -- base=https://roomle.gitlab.io/-/web/example-content/-/jobs/${CI_JOB_ID}/artifacts/dist/
  - >
    curl --request GET --header "Private-Token: ${WEB_CI_PRIVATE_TOKEN}" https://gitlab.com/api/v4/projects/15281206/repository/archive.tar.gz?ref=master > ./archive.tar.gz
  - mkdir -p tools/ && tar xvzf archive.tar.gz -C ./tools && cd tools/* && cp -R ./* ../ && cd ../../
  - node tools/merge-request ${CI_PROJECT_ID} ${CI_MERGE_REQUEST_IID} ${CI_PROJECT_NAMESPACE} ${CI_PROJECT_NAME} ${CI_JOB_ID} 'dist/index.html' ${WEB_CI_PRIVATE_TOKEN}
  - rm -rf tools/
  artifacts:
    paths:
    - dist
    - cache
  only:
  - merge_requests
  when: on_success
